version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: happiness
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  api:
    build: ./api
    container_name: flask_api
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=happiness
      - DB_USER=postgres
      - DB_PASS=postgres
    ports:
      - "5000:5000"
    depends_on:
      - db

  visualization:
    build: ./visualization
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - api
